Update README.md
List Fabric API as a dependency.

Spent a few minutes wondering why my server was crashing on startup with this error. Hopefully making this dependency clear will help others.
[13:46:36] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: easyauth requires {fabric @ [*]}